### ISSUE TITLE
need to install native-graphics-deps prior to running npm install

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/node-gles3#2]
Hi @grrrwaaa 

Npm threw an error when I ran ```npm install``` after a fresh clone, saying that native-graphics-deps/ didn't exist. so I ran ```npm install native-graphics-deps``` first, then did ```npm install```

strange, because     "native-graphics-deps": "0.0.20" is an entry in the package.json

**Comment by grrrwaaa** [comment]
OK figured that out -- it was a matter of the generate script happening before the dependencies (preinstall instead of install) -- that shoudl be fixed. 

Try `rm -rf node_modules && npm install`

There's something odd happening with the created window not showing up, which I'll follow up elsewhere.

**Comment by michaelpalumbo** [comment]
Ok. i ran the rm -rf... message, and received the following (i've omitted the 20 warnings generated)

```shell
20 warnings and 6 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /Users/michaelpalumbo/msvr/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/michaelpalumbo/msvr/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/michaelpalumbo/msvr/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/michaelpalumbo/msvr/node_modules/fsevents
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/michaelpalumbo/msvr/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)

> wrtc@0.4.5 install /Users/michaelpalumbo/msvr/node_modules/wrtc
> node scripts/download-prebuilt.js

node-pre-gyp WARN Using request for node-pre-gyp https download 
[wrtc] Success: "/Users/michaelpalumbo/msvr/node_modules/wrtc/build/Release/wrtc.node" is installed via remote

> nodemon@1.18.11 postinstall /Users/michaelpalumbo/msvr/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by michaelpalumbo** [comment]
> There's something odd happening with the created window not showing up, which I'll follow up elsewhere.

Can confirm this is the same on my machine
